---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - vpn.sunteco.io
  resources:
  - openvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.sunteco.io
  resources:
  - openvpns/finalizers
  verbs:
  - update
- apiGroups:
  - vpn.sunteco.io
  resources:
  - openvpns/status
  verbs:
  - get
  - patch
  - update
